artist1 = Artist.create(name: "Michael Jackson", age: rand(50), title: "King of Pop")
artist2 = Artist.create(name: "Stevie Wonder", age: rand(50), title: "Little Stevie Wonder")
artist3 = Artist.create(name: "Elvis Presley", age: rand(50), title: "the King")
artist4 = Artist.create(name: "Whitney Houston", age: rand(50), title: "The Voice")
artist5 = Artist.create(name: "Beyoncé", age: rand(50), title: "Destiny's Child")

instrument1 = Instrument.create(name: "Guitar", classification: "Strings")
instrument2 = Instrument.create(name: "Violin", classification: "Strings")
instrument3 = Instrument.create(name: "Flute", classification: "Woodwind")
instrument4 = Instrument.create(name: "Xylophone", classification: "Percussion")

join1 = ArtistPlay.create(artist: artist1, instrument: instrument1)
join2 = ArtistPlay.create(artist: artist2, instrument: instrument2)
join3 = ArtistPlay.create(artist: artist3, instrument: instrument2)
join4 = ArtistPlay.create(artist: artist3, instrument: instrument3)
join5 = ArtistPlay.create(artist: artist4, instrument: instrument4)
join6 = ArtistPlay.create(artist: artist5, instrument: instrument4)
